apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omni
  template:
    metadata:
      labels:
        app: omni
    spec:
      containers:
        - name: omni
          image: farah13/omni-app:1.0.0-97
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
          - containerPort: 8080
