---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omni-app:1.0.0-97
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omni-app:1.0.0-97
  template:
    metadata:
      labels:
        app: omni-app:1.0.0-97
    spec:
      containers:
        - name: omni-app:1.0.0-97
          image: farah13/omni-app:1.0.0-97
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
      ports:
        - containerPort: 8080
