pipeline {
	agent {
		label "jenkins-agent"
	}
	
	environment {
		APP_NAME = "OmniApp"
	}
	
	stages{
		stage("Cleanup Workspace"){
			steps{
				cleanWs()
			}
		}
		
		stage("Checkout from SCM"){
			steps{
				git branch: 'main', credentialsId: 'github', url: 'git@github.com:Farah1398/gitops-OmniApp.git'
			}
		}
		
		
		stage("Update the Deployment Tags"){
			steps{
				sh """
					cat deployment.yaml
					sed -i 's/${APP_NAME}.*/${APP_NAME}:${IMAGE_TAG}/g' deployment.yaml
					cat deployment.yaml
				"""
			}
		}
		
		stage("Pysh the changed deployment file to Git"){
			steps{
				
				sh """
					git config --global user.name "farah1398"
					git config --global user.email "farah.ayari@esprit.tn"
					git add deployment.yaml
					git commit -m "Updated Deployment Manifest"
				"""
				
				withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
					sh "git push git@github.com:Farah1398/gitops-OmniApp.git main"
				}
				
			}
		}
		
	}
}
