apiVersion: v1
kind: Service
metadata:
  name: omni-app
  labels:
    run: omni-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: omni-app
